version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=32
      - PMA_HOST=1.2.3.4
      - PMA_USER=admin
      - PMA_PASSWORD=thiZ_is_v&ry_s3cret

  # Node.js application service
  node-app:
    image: myapp
    container_name: node-app
    ports:
      - "5000:3000"
      # Add any other environment variables your Node.js app needs

volumes:
  mongodb_data:


