apiVersion: v1
clusters:
- name: "mycluster"
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJME1ERXhNREUyTXpVek5Wb1hEVE0wTURFeE1ERTJNelV6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTWszCk1UZzY4YTRFUjErMnZvV1l2aWZVTktUQUk1ejNnMlQwMVpBemhjN2RNQThNazJnMEVPT2t6cERPMDkrYnp3enAKUEFTRVVsM09yWDFjR0tOazdJV2ppV0NqUWEyYVBQdHBRY0NKc0pIMDFRVDRyRkVYM2lLYVlJREtMeTdsVDU1cQpnVUFVa2I5RjZTbUJPTVgwV3ZkSmlGdjg2bGRnQjRTTEdWM1d0cE4zbUdCVzMrdFd1cGJvSFJXR3l6dHdSWUd5CmNkazJMcUd5aXJSMGFxZ3o4MkNEeXBWWHFMZVlnZzJla2VpYzlDSlFzSzZqNG00VWtEZE80My9wMy9JVUIwOUMKSzVndTVoZS90S0dWN0FRd2Jwa0M1ck8zN3NkdzJDYm1jb09qSUxjNHVUVUEvWVErNitXKzJES1VCMXNWVm5yKwp0YVdjaGZib0d0S0JKMUQvZzBFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0hRWURWUjBPQkJZRUZGYXU4ZzZVd2xzQml3RWRtWVVMbWVzQzBaVkVNQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDVUZ6aGkwYXNPNU95RFB5bXNrbEFjSmhYWTB5cEFHUlpYcGlaaUZlaEFDSW1CYlBzYQpuZTVJV3NmVnJPRE50SnpiM1phd3JrSURaNEFoYWdNUjloVmYrdlFMR1RxWHlZSXhlYnRSYmE0RnVCZnN6U3hrCkxFQnFvMXBzZEdnQTErSThlMnNNSXFUU3ZzYWl0bVJVT3hsN0czZ0FSYWFXczBNZWNaSGM0ejRKQkFOcjFUUmkKM2xWUmhhaGtUd3JPRUxwV2ZYbERsR3VCQmw4TFpZWHhGcHdRNkxjck5UeVlUamxtaGpQT1BIQUIzYUQ0S0VCdApOVVFHQ2o3b3Z4YitNMTFtOGhFajJhMTRoYkxnRm9sM2kxNWd6djkxRHl2RkZyYU05TjQ5ZXZTejh2djNvelB4CnFDTTVRcXlORlV0a0FXNXlYYms3R1JBRFRqeStHQ1NrVHdKawotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://cba0c3e3-62f0-447a-9851-1dea8a7e5f5c.api.k8s.fr-par.scw.cloud:6443
contexts:
- name: admin@mycluster
  context:
    cluster: "mycluster"
    user: mycluster-admin
current-context: admin@mycluster
kind: Config
preferences: {}
users:
- name: mycluster-admin
  user:
    token: xZQ95Hph4V3eHEUglRKOY2XWtRUqbSbkN5pYDd9yHeHHDT843OUgaa5X